import os
os.environ['T_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

# -*- coding: utf-8 -*-
# Form implementation generated from reading UI file './ui/'
# Created by: PyQt5 UI code generator 5.15.10
# WARNING: Any manual changes made to this file will be lost if pyuic5 is run again.
# Do not edit this file unless you know what you're doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import os
os.environ['T_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"
